routes/admin.php
<?php

use App\Http\Controllers\Admin\AccountController;
use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use Illuminate\Support\Facades\Route;

/**
 * =======================================================
 * Admin Route
 * =======================================================
*/

Route::prefix('admin')->name('admin.')->group(function() {
    Route::get('/login', [AuthController::class, 'loginForm'])->name('login');
    Route::post('/login', [AuthController::class, 'login'])->name('login.submit');
    Route::get('/register', [AuthController::class, 'registerForm'])->name('register');
    Route::post('/register', [AuthController::class, 'register'])->name('register.submit');

    Route::get('/logout', [AuthController::class, 'logout'])->name('logout');
    

    // authenticated
    Route::middleware('auth')->group(function() {
        Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');

        /**
         * ===============================
         * Resource
         * ===============================
         * 
         */
        Route::resource('roles', RoleController::class);
        Route::resource('permissions', PermissionController::class);
        Route::resource('users', UserController::class);
        Route::resource('accounts', AccountController::class);
    });
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

app/Http/Controllers/Admin/AccountController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\AccountRequest;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\View;
use RealRashid\SweetAlert\Facades\Alert;

class AccountController extends Controller
{
    public $view = 'admin.account.';
    public $route = 'admin.accounts.';
    public $title = 'Account';
    public $permission = 'Account';
    public $model;

    public function __construct(User $model)
    {
        $this->model = $model;
        $permission = $this->permission;

        $this->middleware(["permission:$permission index|$permission create|$permission edit|$permission|$permission show|$permission delete"]);

        View::share('title', $this->title);
        View::share('route', $this->route);
        View::share('view', $this->view);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = $this->model->find(auth()->user()->id);
        return view($this->view.'account', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = $this->model->find($id);
        return view($this->view.'edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(AccountRequest $request, $id)
    {
        $input = $request->all();

        if ($input['password'] == null) {
            unset($input['password']);
            unset($input['repeat_password']);
        } else {
            if ($input['password'] !== $input['repeat_password']) {
                Alert::error('Password Different!', 'Failed update data '.$this->title);
                return back();
            }

            // success
            $input['password'] = Hash::make($input['password']);
            $input['repeat_password'] = Hash::make($input['repeat_password']);
        }

        $result = $this->model->find($id)->update($input);

        if ($result) {
            Alert::success('Update Success!', 'Success update data '.$this->title);
            return redirect()->route($this->route.'index');
        }

        Alert::error('Update Failed!', 'Failed update data '.$this->title);
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/account/account.blade.php
@extends('layouts.admin.app')
@section('title', 'Data '.$title)
@section('content')

<div class="row gy-4">
	<div class="col-12 col-lg-12">
		<div class="app-card app-card-account shadow-sm d-flex flex-column align-items-start">
			<div class="app-card-header p-3 border-bottom-0">
				<div class="row align-items-center gx-3">
					<div class="col-auto">
						<div class="app-icon-holder">
							<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-person" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
								<path fill-rule="evenodd" d="M10 5a2 2 0 1 1-4 0 2 2 0 0 1 4 0zM8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm6 5c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
							</svg>
						</div><!--//icon-holder-->
						
					</div><!--//col-->
					<div class="col-auto">
						<h4 class="app-card-title">Profile</h4>
					</div><!--//col-->
				</div><!--//row-->
			</div><!--//app-card-header-->
			<div class="app-card-body px-4 w-100">
				<div class="item border-bottom py-3">
					<div class="row justify-content-between align-items-center">
						<div class="col-auto">
							<div class="item-label mb-2"><strong>Photo</strong></div>
							<div class="item-data"><img class="profile-image" src="{{ asset('assets/images/user.png') }}" alt=""></div>
						</div><!--//col-->
					</div><!--//row-->
				</div><!--//item-->
				<div class="item border-bottom py-3">
					<div class="row justify-content-between align-items-center">
						<div class="col-auto">
							<div class="item-label"><strong>Name</strong></div>
							<div class="item-data">{{ $data->name }}</div>
						</div><!--//col-->
					</div><!--//row-->
				</div><!--//item-->
				<div class="item border-bottom py-3">
					<div class="row justify-content-between align-items-center">
						<div class="col-auto">
							<div class="item-label"><strong>Email</strong></div>
							<div class="item-data">{{ $data->email }}</div>
						</div><!--//col-->
					</div><!--//row-->
				</div><!--//item-->
			</div><!--//app-card-body-->
			<div class="app-card-footer p-4 mt-auto">
				<a class="btn app-btn-secondary" href="{{ route('admin.accounts.edit', auth()->user()->id) }}">Manage Profile</a>
			</div><!--//app-card-footer-->
			
		</div><!--//app-card-->
	</div><!--//col-->
</div><!--//row-->
@endsection

resources/views/admin/account/edit.blade.php
@extends('layouts.admin.app')
@section('title', 'Edit '.$title)
@section('content')

<div class="card">
    <div class="card-body">
        <form action="{{ route($route.'update', $data->id) }}" method="post">
            @method('PUT')
            @include($view.'field')
        </form>
    </div>
</div>

@endsection

resources/views/admin/account/field.blade.php
@csrf

<div class="title mb-3">
    <h6><u>Personal Data</u></h6>
</div>

<div class="mb-3">
    <label for="name">Nama</label>
    <input type="text" name="name" id="name" class="form-control" value="{{ $data->name }}">
</div>
<div class="mb-3">
    <label for="email">Email</label>
    <input type="email" name="email" id="email" class="form-control" value="{{ $data->email }}">
</div>
<hr>

<div class="title mb-3 mt-3">
    <h6><u>Change Password</u></h6>
</div>

<div class="mb-3">
    <label for="password">New Password</label>
    <input type="password" name="password" id="password" class="form-control">
</div>
<div class="mb-3">
    <label for="repeat_password">Repeat Password</label>
    <input type="password" name="repeat_password" id="repeat_password" class="form-control">
</div>
<button class="btn btn-primary text-white">Submit</button>